<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ThunderFury.RarityLoot</AssemblyName>
    <RootNamespace>ThunderFury.RarityLoot</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JotunnLib" Version="2.29.2">
      <ExcludeAssets>runtime</ExcludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
