<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>VikingAdventure.Quests</AssemblyName>
    <RootNamespace>VikingAdventure.Quests</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="assembly_valheim">
      <HintPath>$(ValheimManagedDir)\assembly_valheim.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ValheimManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCoreDir)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCoreDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Jotunn">
      <HintPath>$(BepInExPluginsDir)\Jotunn\Jotunn.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
